system:
  device: cuda
model:
  type: causal
  struct: hf
  name: Qwen/Qwen3-8B
  alias: Qwen3-8B
  torch_dtype: bfloat16
  model_peft: false
  load_in_8bit: false
  custom_modeling: true
  custom_config:
    custom_package_location: resp/modeling
task:
  seed: 0
  project: RESP
  datasets_folder: data
  task_mode: prune
  prune:
    prune_dataset:
      type: open_domain
      name: c4
      seq_len: 2048
      n_samples: 500
    ratio: 0.36
    max_ratio: 0.99
    prune_metric: wanda_sp
    func_name: baseline_uniform_wanda
    prune_modules: all
    prune_separate: true
    prune_skip: true
    act_type: sparse
    custom_pruner: true
    custom_config:
      custom_package_location: resp/pruners
  name: figure2_wanda_c4_30
  output_folder: outputs/figure2_wanda_c4_30
evaluation:
  lm_eval: true
  lm_eval_options:
    output_path: outputs/figure2_wanda_c4_30
    tasks:
    - gsm8k_cot_sample
    num_fewshot:
    - 8
    max_length: 4096
    apply_chat_template: true
    enable_thinking: true
    batch_size: 16
    gen_kwargs:
      do_sample: true
      temperature: 0.6
      max_gen_toks: 2048
    seed: 0
report:
  use_logger: true
  logger:
    log_file_path: outputs/figure2_wanda_c4_30/run.log
  use_wandb: false
